// src/components/GlobalNavComponent.vue
<template>
  <ul class="text-sm">
    <li
      v-for="(article, index) in articles"
      :key="index"
      class="px-4"
      :class="{
        'my-2 py-4 bg-gray-200':
          $page && $page.post.article_number == article.article
      }"
    >
      <g-link
        :to="sectionStarts[article.article].path"
        class="text-gray-700 hover:text-gray-900 px-2 py-1 block"
      >
        <span
          :class="{
            'text-gray-900 font-medium':
              $page && $page.post.article_number == article.article
          }"
          >{{ article.article }}. {{ article.title }}</span
        >
      </g-link>
      <ul
        v-if="$page && $page.post.article_number == article.article"
        class="pl-2"
      >
        <li v-for="(section, index) in $static.allPost.edges" :key="index">
          <g-link
            :to="section.node.path"
            v-if="section.node.article_number == article.article"
            class="text-gray-700 hover:text-gray-900 max-w-full block truncate px-2 py-1"
          >
            <span
              class="truncate"
              :class="{
                'text-gray-900 font-medium':
                  $page && $page.post.title == section.node.title
              }"
              v-html="
                article.article +
                  '-' +
                  section.node.section_number +
                  '. ' +
                  section.node.title
              "
            />
          </g-link>
        </li>
      </ul>
    </li>
  </ul>
</template>

<static-query>
query{
  allPost(sort: [{ by: "article_number", order: ASC }, { by: "section_number", order: ASC }]) {
    edges {
      node {
        title
        article
        article_number
        section_number
        path
      }
    }
  }
}
</static-query>

<script>
import articleList from "~/data/articles.json";

export default {
  name: "GlobalNavComponent",
  data() {
    return {
      articles: articleList
    };
  },
  computed: {
    sectionStarts() {
      let obj = {};
      this.$static.allPost.edges.forEach(page => {
        if (page.node.section_number == 1) {
          obj[page.node.article_number] = page.node;
        }
      });
      return obj;
    }
  }
};
</script>

// app/components/GlobalNavComponent.jsx
import { Link, NavLink, useLoaderData } from "remix";
import groupBy from "lodash/groupBy";

export default function GlobalNavComponent() {
  const { articles } = useLoaderData();

  const articleData = articles.map(a => ({
    article: a.frontmatter.article,
    title: a.frontmatter.title,
    article_number: a.frontmatter.article_number,
    section_number: a.frontmatter.section_number,
    slug: a.slug,
  }))
    .sort((a, b) => { return a.article_number - b.article_number; })
    .sort((a, b) => { return a.section_number - b.section_number; });

  const groupedArticles = groupBy(articleData, "article");

  return (
    <ul className="text-sm">
      {Object.keys(groupedArticles).map((article, idx) => (
        <li key={idx} className="px-4">
          <div
            // to={groupedArticles[article][0].slug}
            className="text-gray-700 hover:text-gray-900 px-2 py-1 block"
          >
            <span>
              {groupedArticles[article][0].article_number}. {article}
            </span>

          </div>
            <ul className="pl-2">
              {groupedArticles[article].map((section, sIdx) => (
                <li key={sIdx}>
                    <NavLink
                      to={`/${section.slug}`}
                      className="text-gray-700 hover:text-gray-900 max-w-full block truncate px-2 py-1"
                  >
                    {({ isActive }) => (
                      <span
                        className={`truncate ${
                         isActive
                            ? "text-gray-900 font-medium"
                            : ""
                        }`}
                      >
                        {section.article_number}.{section.section_number} {section.title}
                      </span>
                    )}
                    </NavLink>
                </li>
              ))}
            </ul>
        </li>
      ))}
    </ul>
  );
}
