// app/components/FigureImg.jsx
import React from "react";

export default function FigureImg({ caption, children }) {
  return (
    <figure className="mb-4">
      <div className="border rounded inline-flex p-1">{children}</div>
      <template v-if="caption">
        <figcaption className="mt-1 text-sm text-gray-700">
          {caption}
        </figcaption>
      </template>
    </figure>
  );
}

// src/components/FigureImg.vue
<template>
  <figure class="mb-4">
    <div class="border rounded inline-flex p-1">
      <slot></slot>
    </div>
    <template v-if="caption">
      <figcaption class="mt-1 text-sm text-gray-700">
        {{ caption }}
      </figcaption>
    </template>
  </figure>
</template>

<script>
export default {
  name: "FigureImg",
  props: ["caption"]
};
</script>
