// src/components/FigureImg.vue
<template>
  <figure class="mb-4">
    <div class="border rounded inline-flex p-1">
      <slot></slot>
    </div>
    <template v-if="caption">
      <figcaption class="mt-1 text-sm text-gray-700">
        {{ caption }}
      </figcaption>
    </template>
  </figure>
</template>

<script>
export default {
  name: "FigureImg",
  props: ["caption"]
};
</script>

// src/components/FigureImg.jsx
import React from 'react'

export default function FigureImg({ caption, children }) {
  return (
    <figure className="not-prose mb-4">
      <div className="inline-flex w-full rounded border p-1">{children}</div>
      {caption ? (
        <figcaption className="mt-1 text-sm text-gray-700">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}
