// src/components/NavbarComponent.tsx
import Image from 'next/image'
import Link from 'next/link'

import { ExternalLink } from 'lucide-react'
import { square } from 'styled-system/patterns'

import Icon from '../../public/meta/bufgreencode-icon.svg'
import Logo from '../../public/meta/bufgreencode-logo.svg'
import SearchComponent from './SearchComponent'

import { css } from 'styled-system/css'

export default function NavbarComponent() {
  return (
    <nav
      className={css({
        pos: 'relative',
        insetX: '0',
        zIndex: '2',
        display: 'flex',
        h: '16',
        flexShrink: '0',
        borderBottomWidth: '1px',
        borderBottomColor: 'gray.200',
        bg: 'white',
      })}
      // className="relative inset-x-0 z-20 flex h-16 shrink-0 border-b border-gray-200 bg-white"
    >
      <div
        className={css({
          pos: 'relative',
          mx: 'auto',
          w: 'full',
          maxW: 'breakpoint-2xl',
        })}
        // className="relative mx-auto w-full max-w-screen-2xl"
      >
        <div
          className={css({
            display: 'flex',
            h: 'full',
            alignItems: 'center',
          })}
          // className="flex h-full items-center"
        >
          <div
            className={css({
              h: 'full',
              flexShrink: '0',
              pl: '4',
              w: {
                base: '16',
                md: '40',
                lg: '72',
                '2xl': '80',
              },
            })}
            // className="h-full w-16 shrink-0 pl-4 md:w-40 lg:w-72 2xl:w-80"
          >
            <div
              className={css({
                display: 'flex',
                h: 'full',
                alignItems: 'center',
              })}
              // className="flex h-full items-center"
            >
              <Link
                href="/"
                className={css({
                  display: 'block',
                  h: 'full',
                  w: 'full',
                  py: '2',
                  lg: {
                    mr: '4',
                  },
                })}
                // className="block h-full w-full py-2 lg:mr-4"
              >
                <Image
                  src={Icon}
                  alt="Buffalo Green Code"
                  className={css({
                    h: 'full',
                    w: 'auto',
                    md: {
                      display: 'none',
                    },
                  })}
                  // className="h-full w-auto md:hidden"
                />
                <Image
                  src={Logo}
                  alt="Buffalo Green Code"
                  className={css({
                    display: {
                      base: 'none',
                      md: 'block',
                    },
                    h: 'full',
                    w: 'auto',
                  })}
                  // className="hidden h-full w-auto md:block"
                />
              </Link>
            </div>
          </div>
          <div
            className={css({
              h: 'full',
              w: 'full',
              flex: '1',
              px: '4',
              md: {
                display: 'block',
                px: '8',
              },
              xl: {
                w: '3/4',
              },
            })}
            // className="h-full w-full flex-1 px-4 md:block md:px-8 xl:w-3/4"
          >
            <div
              className={css({
                display: 'flex',
                h: 'full',
                w: 'full',
                alignItems: 'center',
                py: '2',
              })}
              // className="flex h-full w-full items-center py-2"
            >
              <SearchComponent />
            </div>
          </div>
          <div
            className={css({
              display: {
                base: 'none',
                md: 'flex',
              },
              flexShrink: '0',
              alignItems: 'center',
              pr: '4',
              fontSize: 'sm',
              fontWeight: 'semibold',
              w: {
                lg: '72',
                '2xl': '80',
              },
            })}
            // className="hidden h-full shrink-0 items-center pr-4 text-sm font-medium md:flex lg:w-72 2xl:w-80"
          >
            <Link
              href="/disclaimer"
              className={css({
                px: '2',
                py: '1',
                color: {
                  base: 'gray.600',
                  _hover: 'gray.900',
                },
              })}
              // className="px-2 py-1 text-gray-700 hover:text-gray-900"
            >
              Disclaimer
            </Link>
            <a
              className={css({
                display: 'flex',
                alignItems: 'center',
                px: '2',
                py: '1',
                color: {
                  base: 'gray.600',
                  _hover: 'gray.900',
                },
              })}
              // className="flex items-center px-2 py-1 text-gray-700 hover:text-gray-900"
              href="https://github.com/IHIutch/bufgreencode_v2"
              target="_blank"
              rel="noreferrer"
            >
              <span
                className={css({
                  mr: '1',
                })}
                // className="mr-1"
              >
                Source Code
              </span>
              <span>
                <ExternalLink
                  className={square({ size: '4' })}
                  // className="h-4 w-4"
                />
              </span>
            </a>
          </div>
        </div>
      </div>
    </nav>
  )
}

// src/components/NavbarComponent.vue
<template>
  <nav
    class="flex bg-white border-b border-gray-200 h-16 inset-x-0 flex-shrink-0"
  >
    <div class="w-full max-w-screen-xl relative mx-auto px-6">
      <div class="flex items-center -mx-6 h-full px-6">
        <div
          class="md:w-1/4 lg:w-1/6 pr-4 md:pr-6 lg:pr-8 h-full flex-shrink-0"
        >
          <div class="flex items-center h-full">
            <g-link to="/" class="block lg:mr-4 h-full">
              <img
                src="../assets/images/meta/bufgreencode-icon.svg"
                alt="Buffalo Green Code"
                class="h-full w-auto py-1 md:hidden"
              />
              <img
                src="../assets/images/meta/bufgreencode-logo.svg"
                alt="Buffalo Green Code"
                class="h-full w-auto py-1 hidden md:block"
              />
            </g-link>
          </div>
        </div>
        <div class="md:block flex-grow md:px-4 h-full pl-4 md:pr-2">
          <div class="py-2 h-full">
            <SearchComponent />
          </div>
        </div>
        <div
          class="px-6 h-full hidden md:flex items-center justify-end text-sm font-medium flex-shrink-0"
        >
          <g-link class="py-1 pr-2 text-gray-700 hover:text-gray-900"
            >About</g-link
          >
          <g-link class="py-1 px-2 text-gray-700 hover:text-gray-900"
            >Disclaimer</g-link
          >
          <a
            class="flex items-center py-1 px-2 text-gray-700 hover:text-gray-900"
            href="https://github.com/IHIutch/bufgreencode_v2"
            target="_blank"
            rel="noreferrer"
            ><span class="mr-1">Github</span>
            <span><ExternalLinkIcon size="1x"/></span>
          </a>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
import SearchComponent from "@/components/SearchComponent";
import { ExternalLinkIcon } from "vue-feather-icons";

export default {
  name: "NavbarComponent",
  components: { SearchComponent, ExternalLinkIcon }
};
</script>
